project: 
  type: website
  output-dir: "." 

website:
  title: "Erin Mansfield"
  navbar:
    # background: "#1c4982"
    pinned: true
    left:
      - text: Blog
        href: blog-listing.qmd
      - text: Project
        href: danl_proj_nba.ipynb
      - text: Python Data Analytics 
        menu:
          - text: Panda Basics
            href: pandas_basics.ipynb
          - text: Seaborn Basics
            href: seaborn_basics.ipynb 
      
     
  page-footer: 
    center: "Powered with GitHub, Quarto, and Jupyter Notebook<br>© Erin Mansfield, 2025"

format:
  html:
    theme: 
      light: journal # flatly sandstone yeti united litera journal
      dark: superhero #  darkly cyborg slate solra superhero
    mainfont: system-ui; 
    highlight-style: espresso  # atom-one espresso
    css: styles.css
    toc: false
    include-after-body: target_blank.html

