---
title: "NFL Dashboard"
format:
  dashboard:
    orientation: rows
    theme: cosmo
    vertical_layout: fill
---

```{r}
library(tidyverse)
library(flexdashboard)
library(lubridate)
library(stringr)
```


```{r}
scores <- read_csv("2010-2025_scores.csv")
scores_clean <- scores |>
  mutate(
    GameDate_clean = str_remove(GameDate, "(st|nd|rd|th)$"),
    GameDate_full = paste(GameDate_clean, Season),
    GameDate = suppressWarnings(mdy(GameDate_full)),
    total_points = HomeScore + AwayScore,
    point_diff = abs(HomeScore - AwayScore),
    winner = ifelse(HomeScore > AwayScore, HomeTeam, AwayTeam),
    loser = ifelse(HomeScore < AwayScore, HomeTeam, AwayTeam),
    home_win = HomeScore > AwayScore
  )
regular <- scores_clean |>
  filter(GameStatus == "FINAL") |>
  filter(str_detect(Week, "^WEEK"))

season_summary <- regular |>
  group_by(Season) |>
  summarise(
    avg_points = mean(total_points),
    games = n(),
    high_scoring = sum(total_points >= 50)
  )
```

# Avereage Points by Season
```{r}
ggplot(season_summary, aes(x = Season, y = avg_points)) +
  geom_line(color = "steelblue", linewidth = 1.2) +
  geom_point(color = "steelblue", size =2) +
  labs(
    title = "Average Total Points per Game by Season",
    x = "Season",
    y = "Average Points"
  ) +
  theme_minimal(base_size = 14)
```

# Total Games per Season
```{r}
ggplot(season_summary, aes(x = Season, y = games)) +
  geom_line(color = "darkgreen", linewidth = 1.2) +
  geom_point(color = "darkgreen", size = 2) +
  labs(
    title = "Number of Regular Season Games per Season",
    x = "Season",
    y = "Games"
  ) +
  theme_minimal(base_size = 14)
```

# Average Points by Week
```{r}
avg_points_by_week <- regular |>
  mutate(week_num = as.numeric(str_extract(Week, "\\d+"))) |>
  group_by(week_num) |>
  summarise(avg_points = mean(total_points, na.rm = TRUE))


ggplot(avg_points_by_week, aes(x = week_num, y = avg_points)) +
  geom_col(fill = "darkorange") +
  labs(
    title = "Average Points by Week (all seasons)", 
    x = "Week",
    y = "Average Points"
  ) +
  theme_minimal(base_size = 14)
```


# High Scoring Games per Season
```{r}
ggplot(season_summary, aes(x = Season, y = high_scoring)) +
  geom_col(fill = "purple") +
  labs(
    title = "Number of High Scoring Games per Season",
    x = "Season",
    y = "High Scoring Games"
  ) +
  theme_minimal(base_size = 14)
```


# Team Scoring Heatmap 
```{r}
team_season_points <- regular |>
  mutate(team = HomeTeam, points = HomeScore) |>
  bind_rows(
    regular |>
      mutate(team = AwayTeam, points = AwayScore)
  ) |>
  group_by(team, Season) |>
  summarise(avg_points = mean(points), .groups = "drop")

ggplot(team_season_points, aes(x = Season, y = team, fill = avg_points)) +
  geom_tile(color = "white") +
  scale_fill_viridis_c(option = "plasma", name = "Avg Points") +
  labs(
    title = "NFL Team Scoring Heatmap",
    x = "Season",
    y = "Team"
  ) +
  theme_minimal(base_size = 14) +
  theme(axis.text.y = element_text(size = 8))

```